# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 467933d6cb04c6cd91d368f23fcd4e9ce276c8f371b6a0eb2608a3bc574ce75af12ade702b1eaf3e0588b18deb845912dfa5bae8b8bb4996d7d4c8c77791da60

test:
  secret_key_base: 796ce9f4ef7f53b05905159368481f3a552ae9e32fd229a0aabf7cad016b459dabb0654838c554111348a0247e02df0579ba6cb2aa457b19dc3c0ed09cd341a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
